"""Topics and titles read by hand from handouts whose course plan / header the extractor can't parse.
Used by build_handout_overrides.py. Topics are module / topic names as printed in the handout's plan."""

NO_PLAN = {"topics": [], "notes": ["no_course_plan_in_handout"]}

DIGITAL_DESIGN = ["Working in Binary", "Combinational Building Blocks", "Sequential Design and Building Blocks", "HDL (Verilog)",
                  "Algorithmic State Machines", "Digital Logic Families", "Computer Arithmetic"]
BIOETHICS = ["Introduction to the need and issues governing biosafety",
             "Legal, ethical and social implications including issues related to human reproduction, gene manipulation, genetic testing",
             "Guidelines for research in transgenic organisms and plants such as cloning, stem cell research, gene therapy",
             "Ethics in stem cell research", "Animal cloning and organ transplants", "Biosafety guidelines, regulations, public participation",
             "Socio-economic impacts of biotechnological experiments",
             "Environmental pollution - hazards and control (including disinfection, sterilization, sanitation methods)",
             "CPSEA guidelines", "GLP and GMP guidelines", "Introduction to IPR and Patent processing (self study)"]
VENTURE = ["Orientation Session for Founders, Mentors and SMEs", "Workshop: The Entrepreneurial Mindset", "Workshop: Design Thinking",
           "Workshop: BMC/LMC", "Workshop: Customer Discovery & Market Insights", "Workshop: Building Your Team and HR Fundamentals",
           "Workshop: Funding the Venture", "Workshop: Finance Fundamentals", "Workshop: Operations Management",
           "Workshop: Other People's Technology", "Workshop: Impactful Pitching", "Elevator Pitch", "Pitching - Mock Round",
           "Pitching - Semi-Finals", "Pitching Finals", "1:1 Mentoring + Chamber Hours"]
SMART_MATERIALS = ["Introduction and historical perspective of smart materials and structures", "Smart and intelligent structural systems and applications",
                   "Review of major smart-material families", "Shape-memory alloys", "Electro- and magnetorheological fluids",
                   "Laminated composites and bonded smart structures", "Piezoelectric materials", "Fibre-optic and FBG sensors",
                   "Magnetostrictive and electrostrictive materials", "Applications of smart materials in integrated technologies"]
ADV_NETWORKS = ["Internet Architecture & Principles: design philosophy of the DARPA Internet, end-to-end principle, layers and protocols",
                "Software Defined Networking: SDN architecture, controllers, network programmability, NFV, SDN frameworks",
                "Congestion Control & Traffic Management: TCP congestion control, QUIC, BBR, multipath and QoS routing, FIFO, FQ, RED, CoDel",
                "Wireless & Mobile Networks: Wi-Fi, Mobile IP and micro-mobility protocols, TCP over wireless",
                "Overlay Networks & Data Center Networks: DHT-based overlays, data center architectures, data center TCP"]
MPBA_G504 = ["Introduction to Organizational Behaviour", "Managing Individuals: attitudes and job satisfaction",
             "Individual & Group Dynamics - Motivation", "Managing Groups: Leadership", "Managing Groups: Organizational Structure",
             "Introduction to Human Resource Management", "Job Analysis and Workforce Planning", "Employee Testing and Selection",
             "Learning and Development", "Managing Performance", "Managing Groups: Power, Influence and Politics",
             "Organization System: Managing Culture", "Organization System: Managing Change", "Compensation Management",
             "Managing Future Workforce: career and talent management", "Project and Course Review"]
MPBA_G532 = ["Basis and need for valuation; approaches to valuation (DCF, relative, contingent)", "Economics of a firm; industry, competitive and strategy analysis",
             "Accounting analysis: recasting financial statements, undoing accounting distortions", "Financial analysis: ratio analysis, cash flow analysis, sustainable growth",
             "FCFF vs FCFE", "Cost of capital (WACC): risk and return models, beta", "Forecasting cash flows and growth rates, terminal value",
             "Equity valuation using DCF models (dividends and FCFE)", "Firm valuation using DCF", "Relative valuation: multiples",
             "Mergers and acquisitions"]
PEOPLE_ANALYTICS = ["Getting started with People Analytics", "People Analytics Frameworks", "HR Metrics", "People Analytics as a better tool for HR Decisions",
                    "HR Dashboards", "HR Scorecards", "Statistics in HR", "Insights into Data - HR data and data quality",
                    "Descriptive Analytics (Tableau)", "Understanding Predictive Analytics", "Reporting & Data Visualization",
                    "People Analytics and Digital HR"]

TOPICS_ABOUT = {
    "030_BITS_E584.pdf": NO_PLAN, "068_BITS_G661.pdf": NO_PLAN, "524_PHY_U110.pdf": NO_PLAN,  # plan set per student / in the lab manual
    "058_BITS_F467.pdf": {"topics": BIOETHICS}, "074_BITS_U467.pdf": {"topics": BIOETHICS},
    "059_BITS_F468.pdf": {"topics": VENTURE}, "229_ECON_F415.pdf": {"topics": VENTURE},
    "076_CE_F213.pdf": {"topics": ["Introduction to the Basic Concepts of Surveying", "Linear Measurements and Instruments", "Chain Survey",
                                   "Compass Survey", "Traversing", "Levelling", "Contouring", "Plane Table Survey", "Tacheometric Surveying",
                                   "Curve Ranging", "Trigonometrical Levelling", "Computation of Areas", "Computation of Volumes",
                                   "Advanced Topics in surveying: total stations, errors & adjustments, photogrammetry, remote sensing",
                                   "Practical aspects of field work"]},
    "084_CE_F423.pdf": {"topics": ["Overview of GBEC, climate zones and sun path diagram",
                                   "Thermal comfort, heat flow through building materials, energy efficient building design",
                                   "Site planning, plan form and orientation, construction techniques, materials and finishes",
                                   "Natural day lighting and ventilation strategies, thermal performance of building elements",
                                   "Efficient water management in buildings", "Green building rating systems (GRIHA, LEED)",
                                   "Vernacular architecture in contemporary design; case studies of contemporary green buildings"]},
    "120_CHE_F214.pdf": {"topics": ["Important functional groups and their reactions", "Named reactions (Friedel-Crafts acylation, Beckmann, Aldol, Cannizzaro, Hofmann, Pinacol-Pinacolone, Diels-Alder)",
                                    "Thermodynamics", "Catalysis", "Electrochemistry", "Adsorption", "Chemical methods of analysis (volumetric titrations)",
                                    "Instrumental methods of analysis (IR, UV-Visible spectroscopy, chromatography)", "Fuels and fuel analysis",
                                    "Water and its impurities", "Polymers", "Corrosion"]},
    "143_CHEM_F242.pdf": {"topics": ["Chemoselective reduction of an organic compound", "Multicomponent reaction (Biginelli Reaction)",
                                     "Oxidation of an organic compound (benzil from benzoin)", "Synthesis of benzilic acid from benzil using grinding technique",
                                     "Nucleophilic aromatic substitution", "Separation/purification using column chromatography", "Fischer indole synthesis",
                                     "Coumarin synthesis using microwave irradiation", "Isolation of curcumin from turmeric",
                                     "Photodimerization of benzophenone", "Elemental analysis of known organic compounds",
                                     "Functional group analysis of known compounds", "Complete analysis of unknown compounds",
                                     "Separation of mixtures (techniques I-V) and their analysis"]},
    "151_CHEM_F337.pdf": {"topics": ["Introduction and Tools of Green Chemistry", "Factors for Green Process", "Alternative modes for chemical activation",
                                     "Case studies: Green chemistry", "Basics of Catalysis", "Homogeneous Catalysis - Principles",
                                     "Homogeneous Catalysis - Discussions and Case Studies", "Homogeneous Catalysis - Emerging trends",
                                     "Heterogeneous Catalysts - Principles, Synthesis and Characterizations",
                                     "Heterogeneous Catalysts - Illustrations and Case Studies", "Heterogeneous Catalysts - Emerging Trends"]},
    "159_CHEM_U110.pdf": {"topics": ["Determination of total hardness of water with EDTA", "Estimation of copper by iodometry",
                                     "Determination of the pH curve of an acid-base titration", "Synthesis of dibenzalacetone",
                                     "Colorimetric determination of unknown concentration of K2Cr2O7 solution",
                                     "Dissociation constant of a weak electrolyte by conductometry",
                                     "Validation of Heisenberg's Uncertainty Principle using single-slit diffraction", "Identification of some organic compounds"]},
    "162_CS_F215.pdf": {"topics": DIGITAL_DESIGN}, "205_ECE_F215.pdf": {"topics": DIGITAL_DESIGN},
    "238_EEE_F215.pdf": {"topics": DIGITAL_DESIGN}, "335_INSTR_F215.pdf": {"topics": DIGITAL_DESIGN},
    "176_CS_G525.pdf": {"topics": ADV_NETWORKS}, "177_CS_G525.pdf": {"topics": ADV_NETWORKS},
    "227_ECON_F413.pdf": {"topics": ["Financial engineering: concepts, tools and techniques", "Fixed income securities, term structures, interest rate forwards and futures",
                                     "Pricing bonds, convexity and yield volatility", "Swaps and swap engineering", "Options pricing, option mechanics and options engineering",
                                     "Value at Risk; Monte-Carlo simulation in financial engineering"]},
    "327_HSS_F329.pdf": {"topics": ["Introduction (Art and Fine Arts)", "Melody and Rhythm", "Tonal Sequences", "Musical Scales",
                                    "Principles of Thaat, Raga and Taal", "Voice Culture", "Speed and Multiple speeds", "Acoustics",
                                    "Philosophy and psychology of music", "Aesthetics of music", "Musical Pedagogy", "Notation system",
                                    "Compositional trends", "Merits and demerits of performer", "Study of Raga and Tala"]},
    "329_HSS_F343.pdf": {"topics": ["Introduction: Foundations of Ethics, the Profession and Professional Ethics", "Ethical Theories",
                                    "Professional Codes and Employment Relations", "Business Ethics", "Management Ethics", "Education Ethics",
                                    "Engineering Ethics", "Computer Ethics"]},
    "365_MATH_F311.pdf": {"topics": ["Revision of metric spaces, definition of topology and examples", "Constructing new topological spaces",
                                     "Hausdorff axiom", "Continuity and continuous functions", "Methods for imposing topologies on sets",
                                     "Connectedness", "Compactness", "Countability and separation axioms"]},
    "386_ME_F323.pdf": {"topics": ["Introduction and overview of energy storage", "Mechanical energy storage systems", "Thermal energy storage systems",
                                   "Thermochemical energy storage systems", "Electrochemical energy storage", "Battery technologies",
                                   "Chemical energy storage and fuel cells", "Supercapacitors", "Emerging technologies and CFD modeling"]},
    "391_ME_F428.pdf": {"topics": SMART_MATERIALS}, "409_ME_U428.pdf": {"topics": SMART_MATERIALS},
    "427_MF_F218.pdf": {"topics": ["Introduction to transport phenomena", "Fluid statics", "Fluid kinematics",
                                   "Reynolds transport theorem; mass, momentum and energy conservation", "Steady and transient heat conduction",
                                   "Convective heat transfer (external, internal, natural convection)", "Radiation heat transfer",
                                   "Heat transfer with phase change; simultaneous heat and mass transfer"]},
    "431_MF_F418.pdf": {"topics": ["Birth of lean production", "Lean production system", "Stability and standardized work",
                                   "Just-In-Time and Jidoka", "Value Stream Mapping", "Involvement and customer focus; hoshin planning",
                                   "14 principles of the Toyota way"]},
    "439_MPBA_G504.pdf": {"topics": MPBA_G504}, "440_MPBA_G504.pdf": {"topics": MPBA_G504},
    "463_MPBA_G532.pdf": {"topics": MPBA_G532}, "464_MPBA_G532.pdf": {"topics": MPBA_G532},
    "465_MPBA_G534.pdf": {"topics": PEOPLE_ANALYTICS}, "466_MPBA_G534.pdf": {"topics": PEOPLE_ANALYTICS},
    "039_BITS_F219.pdf": {},  # topics come from the table (flag was the evaluation)
    "180_CS_G527.pdf": {"title": "Cloud Computing"}, "181_CS_G527.pdf": {"title": "Cloud Computing"},
    "224_ECON_F354.pdf": {"title": "Derivatives & Risk Management"},
}
