# Generated by Django 6.1.1 on 2026-09-25 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_tag', models.CharField(max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_by', models.CharField(choices=[('user', 'user'), ('agent', 'agent')], default='user', max_length=5)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.course')),
                ('lecture_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.section')),
                ('practical_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.section')),
                ('tutorial_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.section')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='students.semesterplan')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.CharField(default='Pilani', max_length=30)),
                ('admission_year', models.PositiveSmallIntegerField()),
                ('current_year', models.PositiveSmallIntegerField()),
                ('current_semester', models.PositiveSmallIntegerField()),
                ('minor_registered', models.BooleanField(default=False)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('cgpa_by_semester', models.JSONField(blank=True, default=dict)),
                ('goal', models.CharField(blank=True, default='', max_length=30)),
                ('strengths', models.TextField(blank=True, default='')),
                ('weaknesses', models.TextField(blank=True, default='')),
                ('sop_plan', models.BooleanField(blank=True, null=True)),
                ('minor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.minor')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.programme')),
                ('second_programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.programme')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='semesterplan',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='students.student'),
        ),
        migrations.CreateModel(
            name='ChatState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requests', models.JSONField(blank=True, default=list)),
                ('messages', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_state', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='TimetablePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_8am_days', models.JSONField(blank=True, default=list)),
                ('free_day', models.CharField(blank=True, default='', max_length=2)),
                ('no_saturday', models.BooleanField(default=False)),
                ('avoid_gaps', models.BooleanField(default=False)),
                ('compact', models.BooleanField(default=False)),
                ('priority_order', models.JSONField(blank=True, default=list)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_preference', to='students.student')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='semesterplan',
            unique_together={('student', 'semester_tag')},
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('completed', 'completed'), ('current', 'current')], max_length=10)),
                ('grade', models.CharField(blank=True, max_length=3, null=True)),
                ('semester_taken', models.CharField(blank=True, default='', max_length=30)),
                ('counted_as', models.CharField(blank=True, default='', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
    ]
