# Generated by Django 6.1.1 on 2026-09-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='cgpa_by_semester',
        ),
        migrations.RemoveField(
            model_name='student',
            name='second_programme',
        ),
        migrations.AddField(
            model_name='student',
            name='cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='comfort',
            field=models.CharField(blank=True, choices=[('5', 'Very comfortable'), ('4', 'Comfortable'), ('3', 'Moderate'), ('2', 'Not too comfortable'), ('1', 'Not good at all')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='goal',
            field=models.CharField(blank=True, choices=[('job', 'Job / placement'), ('research', 'Research / higher studies'), ('not_sure', 'Not sure')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('A-', 'A-'), ('B', 'B'), ('B-', 'B-'), ('C', 'C'), ('C-', 'C-'), ('D', 'D'), ('E', 'E'), ('NC', 'NC')], max_length=3, null=True),
        ),
    ]
