# Generated by Django 6.1.1 on 2026-09-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_student_cgpa_by_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourse',
            name='category',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
