# Generated by Django 6.1.1 on 2026-09-25 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentcourse_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='alternative_choices',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
