# Generated by Django 6.1.1 on 2026-09-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_alternative_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='second_degree_code',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
    ]
