# Generated by Django 6.1.1 on 2026-09-26 19:22

import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_second_degree_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='avoid_eval_styles',
            field=models.JSONField(blank=True, default=list, validators=[students.models.validate_eval_styles]),
        ),
        migrations.AddField(
            model_name='student',
            name='default_avoid_8am',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='default_avoid_day',
            field=models.CharField(blank=True, choices=[('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('Th', 'Thursday'), ('F', 'Friday'), ('S', 'Saturday')], default=None, max_length=2, null=True),
        ),
    ]
