# Generated by Django 6.1.1 on 2026-09-27 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_recommender_preferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planitem',
            name='course',
        ),
        migrations.RemoveField(
            model_name='planitem',
            name='lecture_section',
        ),
        migrations.RemoveField(
            model_name='planitem',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='planitem',
            name='practical_section',
        ),
        migrations.RemoveField(
            model_name='planitem',
            name='tutorial_section',
        ),
        migrations.AlterUniqueTogether(
            name='semesterplan',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='semesterplan',
            name='student',
        ),
        migrations.RemoveField(
            model_name='timetablepreference',
            name='student',
        ),
        migrations.DeleteModel(
            name='ChatState',
        ),
        migrations.DeleteModel(
            name='PlanItem',
        ),
        migrations.DeleteModel(
            name='SemesterPlan',
        ),
        migrations.DeleteModel(
            name='TimetablePreference',
        ),
    ]
