# Generated by Django 6.1.1 on 2026-09-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_drop_unused_plan_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='cgpa',
        ),
        migrations.RemoveField(
            model_name='student',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='student',
            name='weaknesses',
        ),
        migrations.RemoveField(
            model_name='studentcourse',
            name='comfort',
        ),
        migrations.RemoveField(
            model_name='studentcourse',
            name='grade',
        ),
        migrations.AddField(
            model_name='student',
            name='did_well',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='student',
            name='grade_oriented',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='struggled',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
