# Generated by Django 6.1.1 on 2026-09-25 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sources', models.JSONField(blank=True, default=dict)),
                ('needs_verification', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, default='')),
                ('category', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, default='', max_length=20)),
                ('group', models.CharField(blank=True, default='', max_length=100)),
                ('min_units', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_units', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('min_courses', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_courses', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('named_courses', models.JSONField(default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sources', models.JSONField(blank=True, default=dict)),
                ('needs_verification', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, default='')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('department', models.CharField(max_length=10)),
                ('L', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('P', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('T', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('S', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('units', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('com_code', models.PositiveIntegerField(blank=True, null=True)),
                ('only_2026_batch', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, default='')),
                ('prerequisites', models.JSONField(blank=True, null=True)),
                ('llm_tags', models.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KnownGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sources', models.JSONField(blank=True, default=dict)),
                ('needs_verification', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, default='')),
                ('gap_id', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('affected', models.JSONField(default=dict)),
                ('user_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Minor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sources', models.JSONField(blank=True, default=dict)),
                ('needs_verification', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, default='')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('min_courses', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('min_units', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('exclusion_text', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sources', models.JSONField(blank=True, default=dict)),
                ('needs_verification', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, default='')),
                ('rule_id', models.CharField(max_length=100, unique=True)),
                ('group', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('values', models.JSONField(default=dict)),
                ('quote', models.TextField(blank=True, default='')),
                ('source_doc', models.CharField(blank=True, default='', max_length=100)),
                ('applies_to_batches', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Handout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sources', models.JSONField(blank=True, default=dict)),
                ('needs_verification', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, default='')),
                ('file', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('learning_outcomes', models.JSONField(default=list)),
                ('topics', models.JSONField(default=list)),
                ('evaluation', models.JSONField(default=list)),
                ('has_midsem', models.BooleanField(null=True)),
                ('open_book_percent', models.FloatField(blank=True, null=True)),
                ('has_project', models.BooleanField(null=True)),
                ('project_percent', models.FloatField(blank=True, null=True)),
                ('has_quiz', models.BooleanField(null=True)),
                ('compre_percent', models.FloatField(blank=True, null=True)),
                ('attendance_text', models.TextField(blank=True, default='')),
                ('attendance_required', models.BooleanField(null=True)),
                ('attendance_percent', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('attendance_follows_default', models.BooleanField(default=False)),
                ('makeup_text', models.TextField(blank=True, default='')),
                ('makeup_allowed', models.BooleanField(null=True)),
                ('makeup_per_component', models.JSONField(default=dict)),
                ('makeup_follows_default', models.BooleanField(default=False)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handouts', to='catalog.course')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HuelPoolCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='huel', to='catalog.course')),
            ],
        ),
        migrations.CreateModel(
            name='MinorCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.course')),
                ('minor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='catalog.minor')),
            ],
        ),
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sources', models.JSONField(blank=True, default=dict)),
                ('needs_verification', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, default='')),
                ('semester_tag', models.CharField(max_length=30)),
                ('campus', models.CharField(max_length=30)),
                ('com_code', models.PositiveIntegerField(blank=True, null=True)),
                ('midsem', models.CharField(blank=True, default='', max_length=30)),
                ('midsem_date', models.CharField(blank=True, default='', max_length=10)),
                ('midsem_session', models.CharField(blank=True, default='', max_length=10)),
                ('compre', models.CharField(blank=True, default='', max_length=30)),
                ('compre_date', models.CharField(blank=True, default='', max_length=10)),
                ('compre_session', models.CharField(blank=True, default='', max_length=10)),
                ('instructor_in_charge', models.CharField(blank=True, default='', max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='catalog.course')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sources', models.JSONField(blank=True, default=dict)),
                ('needs_verification', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, default='')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('degree', models.CharField(blank=True, default='', max_length=30)),
                ('type', models.CharField(choices=[('single', 'single'), ('dual', 'dual'), ('dual_template', 'dual template')], max_length=15)),
                ('edition', models.CharField(blank=True, default='', max_length=20)),
                ('batch_range', models.CharField(blank=True, max_length=50, null=True)),
                ('core_units', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('core_courses', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('del_units', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('del_courses', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('summer', models.JSONField(blank=True, null=True)),
                ('final_year_options', models.JSONField(blank=True, default=list)),
                ('first_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.programme')),
                ('second_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.programme')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PatternSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('semester', models.PositiveSmallIntegerField()),
                ('slot_type', models.CharField(max_length=10)),
                ('alternatives', models.JSONField(default=list)),
                ('elective_category', models.CharField(blank=True, default='', max_length=30)),
                ('units_text', models.CharField(blank=True, default='', max_length=20)),
                ('semester_unit_total', models.CharField(blank=True, default='', max_length=20)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.course')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='catalog.programme')),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammeCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=15)),
                ('component', models.PositiveSmallIntegerField(default=1)),
                ('track_or_pool', models.CharField(blank=True, default='', max_length=100)),
                ('alternative_group', models.JSONField(default=list)),
                ('inferred', models.BooleanField(default=False)),
                ('sources', models.JSONField(blank=True, default=dict)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programme_links', to='catalog.course')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='catalog.programme')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.CharField(max_length=10)),
                ('type', models.CharField(choices=[('lecture', 'lecture'), ('tutorial', 'tutorial'), ('practical', 'practical')], max_length=10)),
                ('instructors', models.JSONField(default=list)),
                ('room', models.CharField(blank=True, default='', max_length=50)),
                ('timings', models.JSONField(default=dict)),
                ('cancelled', models.BooleanField(default=False)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='catalog.offering')),
            ],
        ),
        migrations.CreateModel(
            name='CourseEquivalent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equivalent_code', models.CharField(max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equivalents', to='catalog.course')),
            ],
            options={
                'unique_together': {('course', 'equivalent_code')},
            },
        ),
    ]
