# Generated by Django 6.1.1 on 2026-09-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='handout',
            name='objectives',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='handout',
            name='topic_groups',
            field=models.JSONField(default=list),
        ),
    ]
