# Generated by Django 6.1.1 on 2026-09-26 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_handout_structured_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('title', 'title'), ('description', 'description'), ('topic', 'topic'), ('outcome', 'outcome'), ('bulletin_description', 'bulletin_description')], max_length=25)),
                ('text', models.TextField()),
                ('source', models.CharField(max_length=100)),
                ('embedding', models.BinaryField()),
                ('model_name', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='catalog.course')),
            ],
        ),
    ]
