# Generated by Django 6.1.1 on 2026-09-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_course_piece'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseequivalent',
            name='source',
            field=models.CharField(default='timetable', max_length=10),
        ),
    ]
