# Generated by Django 6.1.1 on 2026-09-28 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_course_equivalent_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='llm_tags',
        ),
    ]
